- scripts/run_graphmod.sh
This just fixes the run_graphmod script to use the current directory structure.
> Fix graphmod script

- x86/src/Data/Macaw/X86/Generator.hs
- x86/src/Data/Macaw/X86/Getters.hs
These `getCallTarget` and `doJump` were calling `fail` if they saw an argument
type that we hadn't thought to handle yet.  This change turns those errors into
TranslationError statements, allowing macaw to continue exploring code.
This came up recently in a glibc-based example where macaw ended up exploring
unaligned code and creating a strange jump to a far pointer, which doesn't make
much sense in x86_64 mode.
> Change some calls to `fail` into translation errors

- .travis.yml
- base/src/Data/Macaw/CFG/App.hs
- base/src/Data/Macaw/Types.hs
- stack.ghc-8.2.2.yaml
- stack.ghc-8.6.3.yaml
- x86/src/Data/Macaw/X86/Getters.hs
- x86/src/Data/Macaw/X86/Monad.hs
- x86/src/Data/Macaw/X86/Semantics/AVX.hs
- x86/src/Data/Macaw/X86/X86Reg.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
- x86_symbolic/src/Data/Macaw/X86/Symbolic.hs
This modifies Macaw in a few ways:
* Support ZMM registers
* Support fixed length vectors.
* Support a bitcast primitive
* Add stack.yaml for 8.6.3.
> Vector improvements

- base/macaw-base.cabal
- base/src/Data/Macaw/Analysis/FunctionArgs.hs
- base/src/Data/Macaw/CFG/DemandSet.hs
- base/src/Data/Macaw/Discovery.hs
- base/src/Data/Macaw/Discovery/State.hs
- base/src/Data/Macaw/Memory.hs
- base/src/Data/Macaw/Memory/ElfLoader.hs
This patch focuses on function argument analysis, but includes some
other cleanups.
The main changes are to add additional comments and cleanups to the
function argument analysis code.  This also extends the analysis so
that we can annotate the types of some of the functions and use those
types during analysis.
As part of this we tighten the PLTStub checking, and clean up the
elfloader in some minor ways.
> Generalize function argument analysis.

- base/src/Data/Macaw/Discovery.hs
- macaw-semmc/src/Data/Macaw/SemMC/TH.hs
Updates to macaw-semmc to accomodate the what4 semiring-based changes.
> Semiring upd

- symbolic/src/Data/Macaw/Symbolic.hs
Update macaw for latest crucible changes from https://github.com/GaloisInc/crucible/pull/283 (specifically https://github.com/GaloisInc/crucible/pull/283/commits/b1f1c4c6098b44155da96415cee96c7abb11e002).
> Crucible recursion bound

- base/src/Data/Macaw/CFG/App.hs
- x86/macaw-x86.cabal
- x86/src/Data/Macaw/X86.hs
- x86/src/Data/Macaw/X86/ArchTypes.hs
- x86/src/Data/Macaw/X86/Monad.hs
- x86/src/Data/Macaw/X86/Semantics.hs
- x86_symbolic/macaw-x86-symbolic.cabal
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
This combines unsigned/signed quotient and remainder into a single operation for each signed/unsigned case.
> Division changes

- macaw-semmc/src/Data/Macaw/SemMC/TH.hs
- stack-8.4.yaml
- stack-8.6.yaml
- x86_symbolic/tests/Main.hs
Updates for inbound crucible changes (see https://github.com/GaloisInc/crucible/pull/329).
> explicit-float-modes

- macaw-ppc/src/Data/Macaw/PPC/Semantics/Base.hs
- macaw-ppc/src/Data/Macaw/PPC/Semantics/TH.hs
- macaw-semmc/src/Data/Macaw/SemMC/TH.hs
This brings it up to master.  The submodule has some improvements to synthesis,
but they changed some APIs.
> Update the semmc submodule

- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/CrucGen.hs
Corresponding changes are now merged into crucible
> Update macaw-symbolic with changes to string literals in what4

- .gitmodules
- cabal.project.dist
I've built `macaw-ppc` and `macaw-ppc-symbolic` with these changes and the `macaw-ppc-tests` seem good-to-go:
```
PPCMacawTests
PPC
tests/ppc/test-conditional.s.expected:    OK
tests/ppc/test-direct-calls.s.expected:   OK
tests/ppc/test-indirect-calls.s.expected: OK
tests/ppc/test-just-exit.s.expected:      OK
tests/ppc/test-fp.s.expected:             OK
PPCCoverage
tests/ppc/bin/gzip:                       OK (53.72s)
All 6 tests passed (53.75s)
```
`macaw-arm` seems to have _unrelated_ build issues currently (which as we've discussed will become irrelevant when the asl-based work finishes):
```
$ cabal v2-build macaw-arm
...
[ 1 of 11] Compiling Data.Macaw.ARM.ARMReg ( src/Data/Macaw/ARM/ARMReg.hs, /Users/andrew/Repos/macaw/dist-newstyle/build/x86_64-osx/ghc-8.6.5/macaw-arm-0.1.0.0/build …
```
> bump semmc submodule, add what4-serialize dep

- macaw-semmc/src/Data/Macaw/SemMC/TH.hs
Commented out guard statements look like haddocks and confuse haddock.
> Fix haddocks for macaw-semmc.

- macaw-ppc/src/Data/Macaw/PPC/Disassemble.hs
This code was confusing what "offset" to pass to the `failAt` function.  Some
sites were passing the offset from the beginning of the block (correct), while
others passed the offset from the start of the segment (incorrect).  The
incorrect values were later used as block sizes, which caused some downstream
failures (in renovate).
This commit uniformly fails with the offset from the start of the block.
> Fix a failure case in the macaw-ppc disassembler logic

- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
Their behavior is not entirely obvious, so hopefully this should be useful to
someone in the future.
> symbolic: Add some documentation on pointer operations

- macaw-semmc/src/Data/Macaw/SemMC/TH.hs
- refinement/src/Data/Macaw/Refinement/Solver.hs
- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
See https://github.com/GaloisInc/what4/pull/55
> [macaw-semmc] updates for app-refactor what4 changes

- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
- refinement/tests/RefinementTests.hs
- symbolic/src/Data/Macaw/Symbolic/Memory.hs
- x86_symbolic/tests/Main.hs
See https://github.com/GaloisInc/crucible/pull/453
> Update for addition of badBehaviorMap implicit for LLVM annotations.

- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
x86 code I've encountered in the wild sometimes contains the following pattern to check for a null pointer argument:
```asm
test %rdi, %rdi
jz .ret
```
Here `test` computes bitwise AND of the arguments and then sets flags. In order to set the zero flag, the semantics for `test` eventually `doPtrEq` the operand with 0. Right now, this always returns a fresh boolean variable, since one argument is a bitvector and the other is a pointer.
> symbolic: Add special cases for null pointers in doPtrEq

- base/macaw-base.cabal
- base/src/Data/Macaw/Analysis/RegisterUse.hs
- utils/compare-dwarfdump/compare-dwarfdump.cabal
- utils/compare-dwarfdump/src/Main.hs
This refactors demand analysis so we export assignment inferred values
and also no longer compute demands for assigments when inference
infers a value for them.
This exposes more information but requires changes to consumers of
information.
> Invariant inference changes.

- base/macaw-base.cabal
- base/src/Data/Macaw/AbsDomain/StackAnalysis.hs
- base/src/Data/Macaw/Analysis/FunctionArgs.hs
- base/src/Data/Macaw/Analysis/RegisterUse.hs
- base/src/Data/Macaw/Discovery.hs
- base/src/Data/Macaw/Discovery/State.hs
- base/src/Data/Macaw/Dwarf.hs
- base/src/Data/Macaw/Memory/ElfLoader.hs
- base/src/Data/Macaw/Utils/IncComp.hs
- x86/macaw-x86.cabal
- x86/src/Data/Macaw/X86/ArchTypes.hs
- x86/src/Data/Macaw/X86/InstructionDef.hs
- x86/src/Data/Macaw/X86/Semantics.hs
- x86/src/Data/Macaw/X86/Semantics/ADX.hs
- x86/src/Data/Macaw/X86/Semantics/AESNI.hs
- x86/src/Data/Macaw/X86/Semantics/AVX.hs
- x86/src/Data/Macaw/X86/Semantics/BMI2.hs
- x86/src/Data/Macaw/X86/Semantics/SHA.hs
This also makes StackAnalysis private to add slightly more control to Macaw's public API.
The Dwarf module was reformatted with Ormolu.
> Improve event handling

- macaw-ppc/src/Data/Macaw/PPC/Arch.hs
This was stubbed out before. It is basically identical to the ppc64 version,
except with offsets corrected.
> ppc32: Add IP alignment rules for code discovery

- symbolic/src/Data/Macaw/Symbolic/PersistentState.hs
I found these useful while printf debugging.
> Add Show{,F} instances for MacawCrucibleValue

- symbolic/src/Data/Macaw/Symbolic/Memory.hs
The `Data.Macaw.Symbolic.Memory` module provides a default memory model and
initial memory setup that is suitable for many symbolic execution
workloads. However, the defaults cannot handle dynamically-linked programs, as
it calls `error` when it attempts to determine an initial value for relocations
it finds in memory.
There are no good defaults for this, as what those values should be depend a lot
on what the verifier wants to prove.
This commit adds some hooks to configure this behavior in the verifier, and is
designed to be extensible and enable other configuration choices where
reasonable.
The original API is unchanged, as it calls the added `newGlobalMemoryWith`
function with a default set of hooks.  Callers with special memory handling
needs are directed to use that function.
> symbolic: Make relocation handling configurable in the symbolic backend

- macaw-aarch32/src/Data/Macaw/ARM/Identify.hs
The return address gets masked and has the low-bit set in an obtuse way due to
the semantics. This threw off the call detection.
This change matches against the quirky pattern.
> Fix a bug in handling return detection in thumb mode

- symbolic/src/Data/Macaw/Symbolic/Memory.hs
This would come in handy for an application where I wish to pass a `NonEmptyVector` to `newMergedGlobalMemoryWith`. Currently, I have to convert the `NonEmptyVector` to a `NonEmpty` list to accomplish this, wish seems wasteful given that `newMergedGlobalMemoryWith` only needs to use the `Foldable` interface.
> Make `newMergedGlobalMemoryWith` work over any `Foldable` collection

- .github/workflows/ci.yaml
- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/Backend.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
> generalize treatment for terminal statements in CFG slicing code

- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
This patch was motivated by the need to call `doGetGlobal` from a Crucible override, where the `SimState` is instantiated with `OverrideLang` rather than `CrucibleLang`, the latter of which is used in the `CrucibleState` type synonym. While I was in town, I generalized the types of other operations in `Data.Macaw.Symbolic.MemOps` where it was reasonable.
> `macaw-symbolic`: Generalize some uses of `CrucibleState` to `SimState`

- base/src/Data/Macaw/Analysis/FunctionArgs.hs
- base/src/Data/Macaw/Analysis/RegisterUse.hs
- base/src/Data/Macaw/CFG/App.hs
- base/src/Data/Macaw/CFG/Block.hs
- base/src/Data/Macaw/CFG/DemandSet.hs
- base/src/Data/Macaw/Discovery.hs
- base/src/Data/Macaw/Discovery/Classifier.hs
- base/src/Data/Macaw/Discovery/ParsedContents.hs
- base/src/Data/Macaw/Discovery/State.hs
- base/src/Data/Macaw/Dwarf.hs
- base/src/Data/Macaw/Fold.hs
- base/src/Data/Macaw/Memory.hs
- base/src/Data/Macaw/SCFG.hs
- base/src/Data/Macaw/Types.hs
These are the least controversial hlint suggestions.
In particular, cleaning up unused pragmas, and redundant syntax that does not help with understanding.
Feel free to disagree with any subset of these!
> applying reasonable hlint suggestions

- base/src/Data/Macaw/Discovery.hs
It can be nice from an external consumer's point of view to have the reason for the exploration of a block.
> explore BlockExploreReason in DiscoveryEvent

- base/src/Data/Macaw/Analysis/RegisterUse.hs
The alignment was all wonky, and one field was not documented.
Someone should double-check that I understood `biUsedAssignSet` correctly.
> fix BlockInvariants docstrings

- base/src/Data/Macaw/Architecture/Info.hs
I'm in the process of pretty-printing more Reopt/Macaw data structures, and need some instances that I will suggest in PRs.
> add Pretty instance for NoReturnFunStatus

- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
This is an exception that consumers might want to catch.
> x86-symbolic: Create an exception type for missing semantics

- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
> x86-symbolic: Structured exceptions for missing primitive function semantics

- base/src/Data/Macaw/Memory/ElfLoader.hs
> `macaw-base`: Fix `R_X86_64_RELATIVE` offset computation

- symbolic/src/Data/Macaw/Symbolic/Testing.hs
> Use Crucible goal-proving helpers in testing code

- base/src/Data/Macaw/AbsDomain/JumpBounds.hs
This is a fix for #424.  The primary fix consists in splitting the logic for equality tests based on the value of `isTrue`.  I have separated it as its own function as it's needed for two branches, and Haskell lacks binding or-patterns.
Along the way, I have made the code for `assertPred` better documented, and much more uniform.  This should make it easier to spot bugs and understand the overall logic.
> fix `assertPred` and make its code more uniform

- macaw-riscv-symbolic/macaw-riscv-symbolic.cabal
- macaw-riscv-symbolic/src/Data/Macaw/RISCV/Symbolic.hs
- macaw-riscv-symbolic/src/Data/Macaw/RISCV/Symbolic/Regs.hs
- macaw-riscv-symbolic/tests/Main.hs
> `macaw-riscv-symbolic`: `Index`es for registers

- macaw-semmc/macaw-semmc.cabal
- symbolic/macaw-symbolic.cabal
There are other release updates that should probably be done but this one is needed right away for saw 😿
> cabal: Allow the new what4 release (1.7)

- base/src/Data/Macaw/Memory/ElfLoader.hs
This downgrades an error in `insertElfSegment` to a warning, represented by the new `ShdrPhdrOverlap` data constructor of `MemLoadWarning`. This allows `macaw-base`'s ELF loader to load binaries where a section header overlaps a program header, which is legal (albeit uncommon) in ELF.
Fixes #485.
> `Data.Macaw.Memory.ElfLoader`: Replace error with `ShdrPhdrOverlap` warning

- .github/workflows/ci.yaml
- .github/workflows/doc.yml
> ci: Upload Haddocks to GitHub pages

- .github/workflows/doc.yml
> ci: Fix Haddock build
