GaloisInc/macaw

- base/src/Data/Macaw/CFG/Rewriter.hs
The parseFetchAndExecute in Discovery attempts to identify ParsedITE
terminal statements by examining the value of the ip_reg via
valueAsApp and pattern matching on a Mux statement.  This patch adds
specific handling in the Macaw CFG Rewriter to attempt to float Mux
statements upwards (aka "Mux Head Normal Form") so that they will be
the top-most ip_reg value and therefore be recognized as a ParsedITE
terminator.
For macaw-ppc testing of the 988KB gzip binary, this increased the
number of blocks found from 1339 to 37950 (and increased the test
runtime from 1.36s to 88.14s).
> Add mhnf rewriting.

- README.md
- macaw-ppc/tests/PPC64InstructionCoverage.hs
Verifies that the number of blocks found matches what should generally
be expected from this particular executable.
The specific value checked for is not independently verified, it just
happens to be a reasonable-looking value that the discovery process
currently identifies, and encoding it here ensures that if discovery
ever changes that the change will be seen and explicitly accepted or
fixed as needed.
> [macaw-ppc] Add test to check the number of blocks found for gzip.

- macaw-ppc-symbolic/src/Data/Macaw/PPC/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/CrucGen.hs
- symbolic/src/Data/Macaw/Symbolic/PersistentState.hs
- x86_symbolic/src/Data/Macaw/X86/Symbolic.hs
- x86_symbolic/tests/Main.hs
Crucible shifted from allowing Unsafe ST-based nonces to the safe IO-based nonces and removed the handle parameterization.  This makes the associated changes necessary in Macaw to accomodate this crucible change.
> Nonce handle deparameterize

- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/CrucGen.hs
- x86_symbolic/tests/Main.hs
Most of the interface functions took a map from addresses to segments, however this map
was never actually used in macaw-symbolic.
The migration for this change is simply to remove the unused parameter from all
call sites in client code.
> Remove an unused parameter from macaw-symbolic

- macaw-ppc/src/Data/Macaw/PPC/Eval.hs
Fixes #80, which removed a type parameter from `IntraJumpBounds`
> Fix macaw-ppc compilation

- macaw-semmc/src/Data/Macaw/SemMC/TH.hs
The improved string support in Crucible adds a parameter to string reprs; this
change accommodates that.  Earlier changes added the necessary support in the
rest of macaw.
> Update macaw-semmc to work with crucible changes

- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
The only real code change required is that simulation failure messages have an
extra argument.  The goal with this update is to pull in some fixes to the
solver feature detection for yices in the latest crucible.
> Update the crucible submodule

- symbolic/src/Data/Macaw/Symbolic/Backend.hs
- symbolic/src/Data/Macaw/Symbolic/MemTraceOps.hs
- x86_symbolic/src/Data/Macaw/X86/Symbolic.hs
Accidentally introduced some warnings in macaw-symbolic on the aarch32 merge
> Fix warnings

- macaw-ppc-symbolic/macaw-ppc-symbolic.cabal
- macaw-ppc-symbolic/src/Data/Macaw/PPC/Symbolic.hs
- macaw-ppc-symbolic/src/Data/Macaw/PPC/Symbolic/Functions.hs
- macaw-ppc/src/Data/Macaw/PPC.hs
- macaw-ppc/src/Data/Macaw/PPC/Arch.hs
- macaw-ppc/src/Data/Macaw/PPC/Disassemble.hs
- macaw-ppc/src/Data/Macaw/PPC/Eval.hs
- macaw-ppc/src/Data/Macaw/PPC/Identify.hs
- macaw-ppc/src/Data/Macaw/PPC/Operand.hs
- macaw-ppc/src/Data/Macaw/PPC/PPCReg.hs
- macaw-ppc/src/Data/Macaw/PPC/Semantics/Base.hs
- macaw-ppc/src/Data/Macaw/PPC/Semantics/PPC32.hs
- macaw-ppc/src/Data/Macaw/PPC/Semantics/PPC64.hs
- macaw-ppc/src/Data/Macaw/PPC/Semantics/TH.hs
This commit reduces duplication by defining some instances in terms of the
parameterized AnyPPC architecture.  It also removes some code that was marked as
deprecated, now that we can use the infrastructure built up around AnyPPC.
> Clean up the PowerPC architecture specifications

- base/src/Data/Macaw/CFG/Rewriter.hs
I think all three of the shifts were erroneous in different ways -- 'BVTestBit' should be 0 when the index is larger than the width of the word. 
Edit: I was wrong; the only bug was the logical shift left case.
> Fixed buggy rewrite rules involving testBit/shifts

- macaw-ppc/tests/PPC64InstructionCoverage.hs
This change is probably due to the BitTrie modifications in
dismantle-tablegen.  It's not clear whether the older or newer number
of discovered blocks is correct; testing at this point is focused more
on getting roughly the correct order of magnitude rather than being
refined enough for high precision values.
> [macaw-ppc] Update test expectations for number of discovered blocks.

- macaw-aarch32/src/Data/Macaw/ARM/Simplify.hs
Under GHC8.4, a let binding is independent of the surrounding context,
so the let statements encountered errors related to type matching on
synthesized internal type parameters that could not be identified as
the same due to rigid skolem type binding inside the let.
> Update for GHC 8.4 type management.

- x86/src/Data/Macaw/X86/Semantics.hs
This change treats them as no-ops (which is what they do on all released
hardware).  We could represent them with arch extensions.  This has a supporting
change in flexdis86 (included as a submodule).
> x86: Add semantics for the endbr instructions

- x86/src/Data/Macaw/X86.hs
- x86/src/Data/Macaw/X86/ArchTypes.hs
- x86/src/Data/Macaw/X86/Semantics/AVX.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
(The corresponding Flexdis86 PR is at GaloisInc/flexdis86#26.)
This PR adds semantics for `vpsrld`, `vpsrlq`, and `vpaddq`.
As an aside, `vpsubd` is currently defined with `avxPointwise2 "vpsubd" PtAdd n32`, which looks suspiciously like it should be `avxPointwise2 "vpsubd" PtSub n32` instead, but maybe I'm missing some wiring somewhere. I've included that change here for now, but I'm amenable to slicing it into its own PR if it's liable to break anything.
> x86: Add semantics for some AVX2 instructions

- x86/src/Data/Macaw/X86/ArchTypes.hs
- x86/src/Data/Macaw/X86/Semantics.hs
- x86/src/Data/Macaw/X86/Semantics/AVX.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
The corresponding decodings are introduced in GaloisInc/flexdis86#27.
> x86: Add semantics for vpunpckhqdq, vxorps, vpaddb, and movbe

- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
- refinement/tests/RefinementTests.hs
- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/Memory.hs
- x86_symbolic/tests/Main.hs
It now requires an action for recording (or discarding) annotations rather than a map.
> Update to use new `HasLLVMAnn` API

- x86/src/Data/Macaw/X86.hs
This is useful downstream sometimes, e.g. for customizing the set of caller/callee saved registers.
> x86: Add some entries to the export list of Data.Macaw.X86

- x86/macaw-x86.cabal
- x86/src/Data/Macaw/X86.hs
- x86/src/Data/Macaw/X86/ArchTypes.hs
- x86/src/Data/Macaw/X86/Semantics.hs
- x86/src/Data/Macaw/X86/Semantics/AESNI.hs
- x86/src/Data/Macaw/X86/Semantics/AVX.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
Namely:
- `aesenc`, `aesenclast`, `aesdec`, `aesdeclast`, `aeskeygenassist`
- `pclmulqdq`
- `psrl{w,d,q,dq}`
- `pshufb`
- `shufps`
- `vpcmpgtd`
The AESNI instructions and `pclmulqdq` work in the same way as the existing `vaesenc`/`vaesenclast`/`vpclmulqdq`, using uninterpreted functions.
> x86: Implement semantics for a few instructions

- .github/workflows/ci.yaml
`add-path` and `set-env` have been deprecated as of 10/1/2020 and will be removed, this patch replaces them with environment files to keep the existing workflows running.
> Replace deprecated GitHub Actions functions

- base/src/Data/Macaw/Dwarf.hs
This enables client code to decode the rest of the DWARF structure (which may
produce errors that we don't want to expose in the macaw-provided API).
> Export the DwarfExpr constructor

- .github/workflows/ci.yaml
- cabal.project.werror
- Use an explicit package-level build step for each architecture, which will
build utility binaries and not just the tests/libraries
- Enable builds/tests for the PowerPC backend
- Build macaw-aarch32-symbolic
Fixes #175
> ci: Have the CI build and test more things

- x86/src/Data/Macaw/X86/Semantics.hs
Fixes are as follows:
- Treat the offset as relative to the end of the destination bitvector instead of the beginning. (A `FIXME` comment mentioned that this might need to be changed, and some testing corroborated this.)
- Only use some instruction-specific number of low bits from the immediate operand. This was resulting in different behavior when the immediate was "too big", for example something like `pinsrd xmm1, eax, 5` should result in an offset of `5 & 0b11 = 1`.
> x86: Fix semantics for pinsrw, add semantics for pinsr{b,d,q}

- macaw-aarch32-symbolic/src/Data/Macaw/AArch32/Symbolic.hs
The previous implementation used all of the registers defined in ASL translator.
It turns out that we don't actually use all of them in macaw; the significant
difference is that the `__memory` pseudo-location is used by asl-translator, but
not macaw (as macaw handles memory through implicit context).  This change
modifies the register assignment to include everything except memory (which
requires an update to the asl-translator submodule).
> aarch32: Change the register context

- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
The operations are correct even when the pointers are not valid LLVM
pointers.
> Remove isValidPtr checks in doPtrSub and doPtrEq.

- .gitignore
- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/Memory.hs
- symbolic/src/Data/Macaw/Symbolic/Testing.hs
* Crucible `mkMemVar` now takes an explicit variable name parameter.
* Fix a doctest for the removal of BaseNatType from What4.
> Match recent Crucible

- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/Backend.hs
There is already an `EvalStmtFunc` defined by Crucible, and while the two are related, the type signature is different.  Changing the name may cause some downstream impact, but there is no other change than the name (other than some formatting updates) and this helps disambiguate any references.
> [symbolic] Rename EvalStmtFunc to MacawEvalStmtFunc

- macaw-aarch32/src/Data/Macaw/ARM/Disassemble.hs
Fix an invalid assumption about absolute addresses that caused an error when analyzing PIE code
> Fix issues analyzing Position Independent Executables in AArch32

- macaw-ppc/src/Data/Macaw/PPC.hs
- macaw-ppc/src/Data/Macaw/PPC/Eval.hs
- refinement/tools/Initialization.hs
None of the common default ppc32 ABIs use a Table of Contents (TOC), so default
our code to not assume it either. This has accompanying changes in
macaw-loader-ppc, which also made incorrect assumptions about ppc32.
Note that we may eventually need to support rarely-used ABIs that do use a
TOC (or similar dedicated registers, e.g., the Small Data Area mode). When we
do, we will probably want that to be a data-oriented decision rather than a
type-level one, as each architecture supports multiple ABIs. We may also need to
modify ppc64 to support ABIs without TOCs, but we'll do it when we need to.
> Fix the default ppc32 ABI

- macaw-aarch32-symbolic/macaw-aarch32-symbolic.cabal
- macaw-aarch32-symbolic/tests/Main.hs
- macaw-ppc-symbolic/macaw-ppc-symbolic.cabal
- macaw-ppc-symbolic/tests/Main.hs
- refinement/macaw-refinement.cabal
- refinement/src/Data/Macaw/Refinement.hs
- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
- refinement/src/Data/Macaw/Refinement/UnknownTransfer.hs
- refinement/tests/RefinementTests.hs
- refinement/tools/Initialization.hs
- refinement/tools/run-refinement.hs
- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
- symbolic/src/Data/Macaw/Symbolic/Testing.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
- x86_symbolic/src/Data/Macaw/X86/Symbolic.hs
- x86_symbolic/tests/Main.hs
GaloisInc/crucible#794 increases the number of functions that use implicit `MemOptions`, including a handful of key LLVM memory model–related functions. As a result, many parts of `macaw` need to add implicit `?memOpts` parameters to accommodate to this change.
> Adapt to GaloisInc/crucible#794

- x86/src/Data/Macaw/X86/ArchTypes.hs
`MemCmp` is essentially a primitive x86 "pseudo-instruction" used to represent computations such as `repz cmps ...` (see it's only usage in the x86 semantics [here](https://github.com/GaloisInc/macaw/blob/9069e114fd309276902dba93eef989c1ab95005a/x86/src/Data/Macaw/X86/Semantics.hs#L1448)).
`MemCmp bpv nv p1 p2 dir` is incorrectly documented to `return the number of bytes that were the same` when the return value is actually the number of `compared values` that were the same, i.e., it's only the number of bytes when`bpv == 1` (i.e., the number of bytes per value is `1`).
Evidence: the returned value is actually the number of _compared values_ of size `bpv` that were the same (as can be seen [here](https://github.com/GaloisInc/macaw/blob/9069e114fd309276902dba93eef989c1ab95005a/x86/src/Data/ …
> doc: fix MemCmp docs w.r.t. semantics of return value

- base/macaw-base.cabal
- base/src/Data/Macaw/AbsDomain/JumpBounds.hs
- base/src/Data/Macaw/Architecture/Info.hs
- base/src/Data/Macaw/CFG.hs
- base/src/Data/Macaw/CFG/Core.hs
- base/src/Data/Macaw/Discovery.hs
- base/src/Data/Macaw/Discovery/Classifier.hs
- base/src/Data/Macaw/Discovery/Classifier/JumpTable.hs
- base/src/Data/Macaw/Discovery/Classifier/PLT.hs
- base/src/Data/Macaw/Discovery/ParsedContents.hs
- base/src/Data/Macaw/Discovery/State.hs
- macaw-aarch32/src/Data/Macaw/ARM.hs
- macaw-aarch32/src/Data/Macaw/ARM/Arch.hs
- macaw-aarch32/src/Data/Macaw/ARM/Eval.hs
- macaw-ppc/src/Data/Macaw/PPC.hs
- macaw-ppc/src/Data/Macaw/PPC/Arch.hs
- macaw-ppc/src/Data/Macaw/PPC/Eval.hs
- refinement/tools/Initialization.hs
- refinement/tools/Summary.hs
- refinement/tools/run-refinement.hs
- x86/src/Data/Macaw/X86.hs
This change makes the block classifier heuristic part of the `ArchitectureInfo`
structure.  This enables clients and architecture backends to customize the
block classification heuristics.  This is most useful for architectures that
have complex architecture-specific block terminators that require analysis to
generate (e.g., conditional returns).  It will also make macaw-refinement
simpler in the future, as the SMT-based refinement is just an additional block
classifier (but is currently implemented via a hacky side channel).
This change introduces an ancillary change, which should not be very
user-visible.
It splits the Macaw.Discovery and Macaw.Discovery.State modules to break
module import cycles in a way that enables us to expose the classifier.  This
should not be user-visible, as …
> Expose block classification in the ArchitectureInfo

- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
- symbolic/ChangeLog.md
- symbolic/src/Data/Macaw/Symbolic/Memory.hs
This:
* Updates the `llvm-pretty-bc-parser` to include these PRs:
* GaloisInc/llvm-pretty-bc-parser#159 (`Support parsing fneg instructions`)
* GaloisInc/llvm-pretty-bc-parser#166 (`Support parsing freeze instructions`)
* GaloisInc/llvm-pretty-bc-parser#164 (`Parse DebugInfoEnumerator properly on LLVM 12+`)
* GaloisInc/llvm-pretty-bc-parser#162 (`Support parsing dict{Associated,Allocated,Rank} fields introduced in LLVM 12`)
The `llvm-pretty` submodule had corresponding changes as well. These were included as part of a previous commit to update the `llvm-pretty` submodule (952fe55), but the `llvm-pretty-bc-parser` submodule was not updated at the same time. This commit brings the two back into harmony.
* Updates the `crucible` submodule to include GaloisInc/crucible#906 (`Control …
> Update llvm-pretty-bc-parser, crucible, semmc submodules; adapt to GaloisInc/crucible#906

- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/CrucGen.hs
- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
Have all additions (at any bit width) go through the special PtrAdd
handler (rather than BVAdd). Also add special handlers for truncation and
extension.
These changes support architectures that do pointer operations at non-pointer
widths (e.g., to detect overflow).  These new operations apply the named
operations over just the offset of pointers, preserving the block id.
Prior to this change, additions at non-pointer bit widths (and also ext/truncs) would throw away the block ID, breaking pointers.
> Revise handling of some pointer operations

- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
> `macaw-symbolic`: Replace `mkName` with `safeSymbol`

- symbolic/src/Data/Macaw/Symbolic/Memory.hs
- symbolic/src/Data/Macaw/Symbolic/Testing.hs
There were two identical definitions of `toCrucibleEndian`, one in `D.M.S.Memory` and another in `D.M.S.Testing`. This commit removes the latter in favor of the former, which is actually exported.
I also added a `fromCrucibleEndian` function, which is useful in similar contexts. `fromCrucibleEndian` is like `toCrucibleEndian`, but in the opposite direction.
> `macaw-symbolic`: Consolidate `toCrucibleEndian` definitions, add `fromCrucibleEndian`

- macaw-aarch32-symbolic/src/Data/Macaw/AArch32/Symbolic/Functions.hs
- macaw-aarch32-symbolic/tests/Main.hs
- macaw-aarch32/src/Data/Macaw/ARM/Semantics/ARMSemantics.hs
- macaw-aarch32/src/Data/Macaw/ARM/Semantics/TH.hs
- macaw-aarch32/src/Data/Macaw/ARM/Semantics/ThumbSemantics.hs
- macaw-ppc-symbolic/src/Data/Macaw/PPC/Symbolic/Functions.hs
- macaw-ppc-symbolic/tests/Main.hs
- macaw-ppc/src/Data/Macaw/PPC/Semantics/PPC32.hs
- macaw-ppc/src/Data/Macaw/PPC/Semantics/PPC64.hs
- macaw-semmc/src/Data/Macaw/SemMC/TH.hs
- macaw-semmc/src/Data/Macaw/SemMC/TH/Monad.hs
- refinement/src/Data/Macaw/Refinement/Solver.hs
- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
- refinement/tests/RefinementTests.hs
- symbolic/ChangeLog.md
- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/Bitcast.hs
- symbolic/src/Data/Macaw/Symbolic/CrucGen.hs
- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
- symbolic/src/Data/Macaw/Symbolic/Memory.hs
- symbolic/src/Data/Macaw/Symbolic/Testing.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
- x86_symbolic/tests/Main.hs
This mostly deals with the splitting of the old `sym` type into
two: one for dealing with expression creation, and a new simulator
backend type for dealing with control-flow and assertions.
> Update with changes flowing from GaloicInc/crucible#945.

- symbolic/src/Data/Macaw/Symbolic/CrucGen.hs
Closes #234 
This change modifies `addMacawParsedTermStmt` to translate `PLTStub`s as
tail calls.
> Translate PLTStubs as tail calls

- macaw-aarch32-symbolic/src/Data/Macaw/AArch32/Symbolic.hs
- macaw-aarch32-symbolic/src/Data/Macaw/AArch32/Symbolic/Functions.hs
- macaw-ppc-symbolic/src/Data/Macaw/PPC/Symbolic.hs
- macaw-ppc-symbolic/src/Data/Macaw/PPC/Symbolic/Functions.hs
- symbolic/ChangeLog.md
- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/Backend.hs
- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
- symbolic/src/Data/Macaw/Symbolic/Testing.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
- x86_symbolic/src/Data/Macaw/X86/Symbolic.hs
This is the same patch as #203, but rebased and with an additional commit to parameterize `Lookup{Function,Syscall}Handle` by the `personality` type variable, which proves handy in my particular use case. I've also added another commit to note these changes in the `macaw-symbolic` changelog.
> Only fix personality to (MS.MacawSimulatorState sym) where required. (take two)

- .github/workflows/ci.yaml
- README.md
This PR updates the softfloat-hs submodule to a version that doesn't require a manual `make` and `make install` over the softfloat library.
> Update softfloat-hs repo to eliminate manual build step

- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
- symbolic/ChangeLog.md
- symbolic/src/Data/Macaw/Symbolic/Memory.hs
Before, the API provided by macaw-symbolic asserted the initial value of each byte of memory individually. This was fairly expensive for large binaries, as each such assertion flushed the solver pipe.
This change generates a large conjunction of assertions and sends them all at once. In unscientific testing, this saved half an hour on a large binary.
API Changes:
- Note that it introduces a minor API change. The optimization required that the `sym` parameter be concretely an `ExprBuilder`.
> [symbolic] Optimize how initial binary memories are populated

- symbolic/src/Data/Macaw/Symbolic/Memory.hs
This change adds a function `newMergedGlobalMemoryWith`, which acts like
`newGlobalMemoryWith` but takes a list of macaw memories and merges them
into a flat address space.  This aids in reasoning dynamically linked
programs.
> Add ability to load multiple memories into a flat address space

- base/src/Data/Macaw/Discovery.hs
This is necessary to implement custom logic using the incremental computation
monad, as the even lower-level infrastructure is not exposed at all.
> Export an extra function from the discovery API

- base/src/Data/Macaw/Memory.hs
The ```R_X86_64_COPY``` has a zero size (because the actual size depends on the symtab) and so causes problems when constructing the Memory contents.  This PR ignores those relocations as a temporary workaround until a better solution is available (See #47)
> Ignore relocations with zero size when constructing Memory

- .github/workflows/ci.yaml
- base/ChangeLog.md
- base/src/Data/Macaw/Memory/ElfLoader.hs
This bump the `elf-edit` submodule to bring in the changes from GaloisInc/elf-edit#29, which adds an additional `VersionDefMap` argument to `elf-edit` to make it aware of version definitions. This requires some changes to the API in `Data.Macaw.Memory.ElfLoader` to accommodate.
> Adapt to `dynSymEntry` being definition-aware in `elf-edit`

- macaw-aarch32/src/Data/Macaw/ARM/Arch.hs
- macaw-riscv/src/Data/Macaw/RISCV/Disassemble.hs
- x86/src/Data/Macaw/X86/Generator.hs
When a user overrides a system call on an architecture that supports returning two values from a system call and they provide a context containing the result of the system call in the form
```
empty :> v0 :> v1
```
macaw will perform the register assignment
```
r0 := v1
r1 := v0
```
This change reverses this behavior so that the assignment becomes
```
r0 := v0
r1 := v1
```
This brings the expected ordering of the result context in agreement
with the left-to-right ordering of the argument context:
```
empty :> arg1 :> arg2 :> ...
```
> Reverse syscall override return register ordering

- symbolic/ChangeLog.md
- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
This bumps the `crucible` submodule to bring in the changes from GaloisInc/crucible#998, which adds `?memOpts :: MemOptions` constraints to a handful of additional functions. This requires adding constraints to some functions in `macaw-symbolic` to accommodate, as well as bumping the `semmc` submodule to bring in analogous changes from GaloisInc/semmc#76.
> Adapt to GaloisInc/crucible#998

- symbolic/ChangeLog.md
- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
The internal memory model operations already assert the same checks.
CF #300
> Remove redundant "valid pointer" checks from memory loads and stores.

- base/src/Data/Macaw/Memory/ElfLoader.hs
We already have support for `R_X86_64_COPY` relocations, so adding support for `R_ARM_COPY` on the AArch32 side is straightforward.
This is related to #47, although this is not a full fix for the issue.
> `macaw-base`: Support loading `R_ARM_COPY` ELF relocations

- symbolic/ChangeLog.md
- symbolic/src/Data/Macaw/Symbolic/Memory.hs
When populating `COPY` relocations, it is helpful to know the address of the relocation so that it can be related back to the name of the global symbol whose value it is copying. Unfortunately, the type of `populateRelocation` does not make it straightforward to compute this address. This patch includes three additional arguments to `populateRelocation` (the relocation's `Memory`, its `MemSegment`, and its `MemAddr`) to more easily facilitate computing the address.
This is a breaking API change, albet it is a fairly straightforward change to adapt to for most consumers.
This is related to #47, although this is not a full fix for the issue.
> `macaw-symbolic`: Include addresses in `populateRelocation`

- base/ChangeLog.md
- base/src/Data/Macaw/CFG/App.hs
- base/src/Data/Macaw/CFG/AssignRhs.hs
- base/src/Data/Macaw/CFG/Core.hs
- base/src/Data/Macaw/Types.hs
Either we want to put an explicit upper bound on hashable (which is currently not explicitly listed, but is depended upon transitively via parameterized-utils re-exporting `Hashable` in `Data.Parameterized.Classes`), or we can sprinkle in a couple of `Eq` instances like so.
Not sure who to review this, but since @RyanGlScott you've been doing such changes elsewhere, maybe you have an opinion on this!
> support hashable-1.4

- .github/workflows/ci.yaml
One issue was that we were computing the restore key on the hash of a file before creating said file when restoring, but after creating the file when saving, so there was a constant mismatch.
The second issue is that we were not caching dist-newstyle, so we would always rebuild our "local" dependencies such as binary-symbols, elf-edit, etc.
> fix CI slowness issues

- .github/workflows/ci.yaml
I pushed before the previous GHC 8.10.7 built finished, so it's lagging behind, but looks like this works!
> bump obsolete CI actions

- base/src/Data/Macaw/Discovery/Classifier.hs
This was the only classifier error message not capitalized.
> make error casing uniform

- macaw-aarch32/src/Data/Macaw/ARM/Disassemble.hs
- macaw-ppc/src/Data/Macaw/PPC/Disassemble.hs
`macaw-ppc` was previously assuming that addresses are absolute, which is not true for position independent executables. Extracting the offset from the address is sufficient for our purposes here (note that taking the offset from the `MemSegmentOffset` would not be right, as that offset is relative to the segment start).
This is the exact same issue that was noticed in https://github.com/GaloisInc/macaw/commit/37d8029c00d99335625ab615c7ae94fba18f9574 (in `macaw-aarch32`), but that commit forgot to fix things on the `macaw-ppc` end.
> `macaw-ppc`: Don't assume absolute IP addresses when decoding

- base/src/Data/Macaw/Analysis/FunctionArgs.hs
It's sometimes practical to debug the map of analysis failures by printing them all out, but we don't seem to have any facilities for printing them.
> derive `Show` for `FunctionArgAnalysisFailure`

- symbolic/src/Data/Macaw/Symbolic.hs
- symbolic/src/Data/Macaw/Symbolic/MemOps.hs
- symbolic/src/Data/Macaw/Symbolic/Memory/Lazy.hs
This introduces a `HasMacawLazySimulatorState` data type, which provides a "classy lens" for accessing a `MacawLazySimulatorState` within some Crucible personality type. It also generalizes the lazy `macaw-symbolic` memory model in `Data.Macaw.Symbolic.Memory.Lazy` to be polymorphic over `HasMacawLazySimulatorState` instances. The upside is that it is now possible to use the lazy memory model at other personality types besides just `MacawLazySimulatorState`, making it much easier to extend the memory model.
Because there is a `HasMacawLazySimulatorState` instance for `MacawLazySimulatorState`, existing code that uses `MacawLazySimulatorState` should continue to compile without changes.
Fixes #357.
> Generalize lazy memory model using `HasMacawLazySimulatorState`

- macaw-aarch32-symbolic/src/Data/Macaw/AArch32/Symbolic.hs
- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
> {aarch32,x86}-symbolic: A bit more work on exceptions

- symbolic/src/Data/Macaw/Symbolic/Memory/Common.hs
> `macaw-symbolic`: Fix interval bounds in `mkGlobalPointerValidityPred`

- base/src/Data/Macaw/Types.hs
Makes it possible to derive a `Show` instance for a datatype including a `Some FloatInfoRepr`.
> add ShowF instance for FloatInfoRepr

- .github/workflows/ci.yaml
Looks like all CI actions succeeded. No more warnings.
> bump CI actions versions

- refinement/src/Data/Macaw/Refinement/Path.hs
We encountered a binary that caused a panic due to `insertLabeledEdge` returning `Nothing`.
It seems like this could happen in one of two cases:
- The source or the destination vertex doesn't exist
- An edge between source and destination already exists
By using `replaceLabeledEdge` instead, we can avoid panicking in the second case where refinement execution can proceed without issue.
However, it would be nice to make sure that the appearance of a parallel edge isn't an indicator of a larger issue in the algorithm, or if using `replaceLabeledEdge` is a good enough fix.
> Fix refinement panic with parallel CFG edges

- base/ChangeLog.md
- base/src/Data/Macaw/Dwarf.hs
This is useful for Reopt as we want to get more accurate type information for library functions.
Is this acceptable for other clients?
> parse subroutine type declaration formal parameters

- README.md
> Cite Macaw paper and blog post in the README

- base/src/Data/Macaw/Memory.hs
A future fix I'm going to submit would benefit from having this exposed, and we believe this to be a good idea regardless.
> expose `memInt` in `Memory`

- base/src/Data/Macaw/Memory.hs
Note: this made me realize that `addrBitSize` is a bit ill-named as I don't think it has anything to do with addresses.
> add a `Bits` instance to `MemInt`

- base/src/Data/Macaw/AbsDomain/JumpBounds.hs
Given some symbolic value, `x`, we'd like to compute its possible upper and lower bounds after it is truncated to `w` bits.
To do this, we first find the bound of x by (recursively) calling `exprRangePred`. This bound is a statement of the following form (see `RangePred` for more info): "`r` bits of `x` are bounded between `low` and `high`".
Then, we check the following:
- If `x` has a bound `(r, l, h)` AND
- If `r` is less than or equal to `w` => Pass-through the bound `(r, l, h)`
Otherwise, we deem `x` "unbounded"
Declaring `x` unbounded in the second case seems to throw away useful information that causes many jump tables to remain unclassified. We attempt to improve on that in this commit.
Consider an example where `x` is bounded by `(64, 0, 10)` (that is, the 64 bits of `x` are …
> Improve handling of JumpBound truncation constraints

- base/src/Data/Macaw/Analysis/RegisterUse.hs
For some reason we were very conservative in our support or abstract
operations over the processor state in the `RegisterUse` analysis.
In particular, we were failing to process code such as:
r23 := (bv_and r21 (0xfffffffffffffff0 :: [64]))
whose goal is to align the value in r21 at a 16-byte boundary.
This resulted in us failing to analyze some code that was realigning its
stack pointer.  With this change, the same code succeeds at propagating
the abstract stack pointer offset forward.
> support alignment ops when processing statements in `RegisterUse`

- macaw-ppc-symbolic/src/Data/Macaw/PPC/Symbolic.hs
- macaw-ppc-symbolic/src/Data/Macaw/PPC/Symbolic/Functions.hs
- macaw-ppc/src/Data/Macaw/PPC/Arch.hs
- macaw-ppc/src/Data/Macaw/PPC/Eval.hs
This PR contains a collection of commits needed to bring `macaw-ppc-symbolic`'s handling of system calls and semantics-related exceptions in line with `macaw-x86-symbolic` and `macaw-aarch32-symbolic`:
Fixes https://github.com/GaloisInc/macaw/issues/385 (and finishes the work started in https://github.com/GaloisInc/macaw/pull/370).
This adds the necessary changes to `macaw-ppc-symbolic` and `macaw-ppc` in order to simulate system calls, similarly to how it is done when simulating x86-64 and AArch32 code:
* In `macaw-ppc`, remove `PPCSyscall` from `TermStmt` and instead make it a constructor for `PPCPrimFn`. (Note that there are some minor discrepancies between which registers are used in PPC32 versus PPC64, which we explain in the Haddocks for the new `PPCSyscall` constructor.)
* Update …
> `macaw-ppc-symbolic`: Add syscall support, export `SemanticsError`

- symbolic/macaw-symbolic.cabal
- symbolic/src/Data/Macaw/Symbolic/Stack.hs
- symbolic/src/Data/Macaw/Symbolic/Testing.hs
Factors some code out of `Testing` into its own module for the sake of clarity and code-sharing. Several downstream projects could benefit from this API, see #430 for examples.
Also, rewrites a comment that I believe to have been misleading.
> symbolic: Factor stack setup code into its own module

- .github/workflows/lint.yml
- symbolic/.hlint.yaml
- symbolic/src/Data/Macaw/Symbolic.hs
There was a lot of redundant unwrapping and re-wrapping of the assignment of `TypeRepr`s to the architecture register context into and out of a `StructRepr`. Remove this.
Also, add an hlint configuration file to help avoid this in the future, and a Github Actions workflow to enforce this in CI.
> symbolic: Remove redundant unwrapping/rewrapping of register struct

- macaw-aarch32-symbolic/tests/Main.hs
- macaw-aarch32-symbolic/tests/README.org
- macaw-ppc-symbolic/tests/Main.hs
- macaw-ppc-symbolic/tests/README.org
- macaw-riscv-symbolic/tests/Main.hs
- macaw-riscv-symbolic/tests/README.org
- symbolic/src/Data/Macaw/Symbolic/Testing.hs
- x86_symbolic/macaw-x86-symbolic.cabal
- x86_symbolic/src/Data/Macaw/X86/Symbolic.hs
- x86_symbolic/src/Data/Macaw/X86/Symbolic/ABI/SysV.hs
- x86_symbolic/tests/Main.hs
- x86_symbolic/tests/README.org
>  x86-symbolic: Setting up a SysV-compatible stack 

- x86_symbolic/src/Data/Macaw/X86/Symbolic/ABI/SysV.hs
> x86-symbolic: Establish SysV stack alignment

- macaw-aarch32-symbolic/src/Data/Macaw/AArch32/Symbolic.hs
- macaw-aarch32-symbolic/tests/Main.hs
... like the ones for x86_64. These will help in development of a concrete syntax for macaw-symbolic-aarch32, and can be helpful when setting up or interpreting the results from symbolic execution.
> aarch32-symbolic: Named `Index`es into `ArchRegContext AArch32`

- macaw-aarch32-symbolic/macaw-aarch32-symbolic.cabal
- macaw-aarch32-symbolic/src/Data/Macaw/AArch32/Symbolic/ABI.hs
- macaw-aarch32-symbolic/tests/Main.hs
- symbolic/src/Data/Macaw/Symbolic/Stack.hs
- x86_symbolic/src/Data/Macaw/X86/Symbolic/ABI/SysV.hs
- x86_symbolic/tests/Main.hs
Like #433 + #437, but for AArch32. Towards #430. Based on #438. Needs to be integrated into the test suite for validation.
> aarch32-symbolic: Setting up an ABI-compatible stack

- macaw-riscv/src/Data/Macaw/RISCV/RISCVReg.hs
> `macaw-riscv`: Define ABI mnemonics for floating-point registers

- x86_symbolic/src/Data/Macaw/X86/Crucible.hs
- Phrase them in terms of abstractions users can understand (instructions, rather than our internal representation of x86_64 semantics)
- Don't negate what has happened
> x86-symbolic: Improve div-by-zero error messages

- symbolic-syntax/README.md
- symbolic-syntax/src/Data/Macaw/Symbolic/Syntax.hs
- symbolic-syntax/test-data/ops.cbl
- symbolic-syntax/test-data/ops.out
- symbolic-syntax/test-data/ops.out.good
> `macaw-symbolic-syntax`: Add concrete syntax for `BitsToPtr` and `PtrToBits`

- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
This bumps the following submodules:
* `crucible`, to bring in the changes from https://github.com/GaloisInc/crucible/pull/1331 (the primary purpose of this patch)
* `asl-translator`, to bring in the changes from https://github.com/GaloisInc/asl-translator/pull/57 to stay in sync with `crucible`.
* `llvm-pretty`, `llvm-pretty-bc-parser`, and `what4`, which are necessary to stay in sync with `crucible`.
https://github.com/GaloisInc/crucible/pull/1331 adds a new field to `AbortedExit`, which `macaw-refinement` pattern-matches on in `Data.Macaw.Refinement.SymbolicExecution`. As such, this patch also makes a minor code change to keep that particular bit of code compiling.
> Bump submodules, adapt to changes in GaloisInc/crucible#1331

- macaw-dump/macaw-dump.cabal
- macaw-dump/src/Data/Macaw/Dump.hs
- macaw-dump/src/Data/Macaw/Dump/CLI.hs
- macaw-dump/src/Data/Macaw/Dump/CLIUtils.hs
- macaw-dump/src/Data/Macaw/Dump/EntryPoints.hs
- macaw-dump/src/Data/Macaw/Dump/Memory.hs
This prints the entry point addresses computed by `macaw-loader`. This proves useful to debug issues like the one observed in https://github.com/GaloisInc/macaw/issues/482.
> `macaw-dump`: Add `entry-points` subcommand

- macaw-loader-aarch32/src/Data/Macaw/BinaryLoader/AArch32.hs
- macaw-loader-ppc/src/Data/Macaw/BinaryLoader/PPC.hs
- macaw-loader-riscv/src/Data/Macaw/BinaryLoader/RISCV.hs
- macaw-loader-x86/src/Data/Macaw/BinaryLoader/X86.hs
- macaw-loader/src/Data/Macaw/BinaryLoader.hs
- refinement/tools/Initialization.hs
It is not guaranteed that an ELF file's `e_entry` value will always correspond to a valid entry point address, which means that we cannot guarantee that the list of entry points that `macaw-loader`'s `entryPoints` computes will always be non-empty. This patch changes the type of `entryPoints` to return `[]` instead of `NonEmpty` and makes it so that failing to resolve the `e_entry` address in `entryPoints` does not throw an exception.
Fixes https://github.com/GaloisInc/macaw/issues/482.
> `macaw-loader`: Make `entryPoints` return a possibly empty list

- symbolic/src/Data/Macaw/Symbolic/Memory.hs
- symbolic/src/Data/Macaw/Symbolic/Memory/Common.hs
- symbolic/src/Data/Macaw/Symbolic/Memory/Lazy.hs
Not quite working yet. Although this fixes the test case in #491, it does _not_ fix the corresponding test case from https://github.com/GaloisInc/grease/issues/187.
Towards #491.
> `macaw-symbolic`: Fix soundness bug in lazy memory model involving path conditions

- macaw-dump/src/Data/Macaw/Dump/CLI.hs
After these changes, the `--help` text for subcommands are much more descriptive, e.g.,
```
$ cabal -v0 run exe:macaw-x86-dump -- discover --help
Usage: macaw-x86-dump discover FILENAME [SYMBOL] [--crucible]
Perform code discovery and print CFGs
Available options:
FILENAME                 filename of binary
SYMBOL                   function name
--crucible               output Crucible CFGs
-h,--help                Show this help text
```
Fixes https://github.com/GaloisInc/macaw/issues/510.
> `macaw-dump`: Show `--help` text for all subcommands 

- base/src/Data/Macaw/Memory/ElfLoader.hs
There is no particularly good reason to disallow loading file types like `ET_NONE` or `ET_CORE`, as `memoryForElf` (another ELF-loading function in the same module) can handle them without issues.
Fixes #512.
> resolveElfContents: Allow loading any ELF file type

- macaw-aarch32-symbolic/tests/Main.hs
- macaw-x86-cli/src/Data/Macaw/X86/Symbolic/CLI.hs
- refinement/src/Data/Macaw/Refinement/SymbolicExecution.hs
- refinement/tests/RefinementTests.hs
- symbolic/src/Data/Macaw/Symbolic/Memory.hs
- symbolic/src/Data/Macaw/Symbolic/Memory/Common.hs
- symbolic/src/Data/Macaw/Symbolic/Memory/Lazy.hs
- symbolic/src/Data/Macaw/Symbolic/Testing.hs
- x86_symbolic/tests/Main.hs
Note i removed the fact that this closes the referenced issue as this only adds the error which we would like to refine in Grease currently.
The original issue is #429
> Add a MacawProcessAssertion implicit callback for recording macaw memory model predicates

- symbolic/src/Data/Macaw/Symbolic/Memory/Lazy.hs
> `macaw-symbolic`: Re-export `MacawProcessAssertion` et al. from `Data.Macaw.Symbolic.Memory.Lazy`

- symbolic/src/Data/Macaw/Symbolic/CrucGen.hs
- symbolic/src/Data/Macaw/Symbolic/Testing.hs
> symbolic: Avoid recomputing `crucGenRegStructType`
